#[derive(Debug, Clone)]
pub enum Action {
    FocusChange,
    Tick,
    Key(crossterm::event::KeyEvent),
    MouseClick(u16, u16),
    Quit,
    GoBack,
    SelectLanguage(usize),
    Resize(u16, u16),
    ToggleHelp,
    ToggleTvMode,
    SwitchToStreamingMode,
    SwitchProvider(pulse_core::providers::models::ProviderKind),
    ShowTvConfig,
    TvChannelsLoaded(Vec<pulse_core::providers::tv::Channel>, usize),
    TvPlaylistAdd(String),
    TvPlaylistRemove(usize),
    TvReloadPlaylists,
    TvInputToggle(bool),
    ShowAddonManager,
    AddonAddManifest(String),
    AddonToggleEnabled(usize),
    AddonRemove(usize),
    AddonInputToggle(bool),
    Search {
        query: String,
        force_refresh: bool,
    },
    SelectSuggestion {
        query: String,
    },
    SearchSuccess {
        context: pulse_core::providers::models::RequestContext,
        request_id: u64,
        query: String,
        page: usize,
        items: Vec<pulse_core::providers::models::CatalogItem>,
    },
    SearchFailure(
        pulse_core::providers::models::RequestContext,
        u64,
        usize,
        String,
    ),
    FetchHomepage {
        tab_id: String,
        page: usize,
    },
    HomepageSuccess {
        request_id: u64,
        tab_id: String,
        page: usize,
        items: Vec<pulse_core::providers::models::CatalogItem>,
        metrics: std::collections::HashMap<String, pulse_core::models::BrowseMetrics>,
    },
    HomepageFailure(u64, String),
    Suggest(String),
    SuggestSuccess(u64, String, Vec<String>),
    MoveUp,
    MoveDown,
    MoveLeft,
    MoveRight,
    WheelScroll {
        up: bool,
    },
    Submit,
    TabPane,
    BackTabPane,
    FetchPreview(String),
    PreviewSuccess(
        u64,
        String,
        Box<pulse_core::providers::models::MediaDetails>,
    ),
    PreviewFailure(u64, String),
    PlayStream,
    ShowSubtitlePopup(String, Vec<pulse_core::providers::models::SubtitleOption>),
    ShowDownloadSubtitlePopup(Vec<pulse_core::providers::models::SubtitleOption>),
    ToggleThemePopup,
    SelectTheme(String),
    ToggleSettingsPopup,
    SelectSettingsCategory(crate::tui::state::SettingsCategory),
    SettingsAdjustValue(bool),
    SettingsActivateRow,
    SettingsResetDownloadDir,
    ShowBrowseMenu,
    SelectBrowse(crate::tui::state::BrowsePreset),
    SelectAddonCatalog(pulse_core::providers::addons::models::AddonCatalogTarget),
    DownloadStream(Option<String>),
    StartDownload(Option<String>, Option<String>, Vec<(String, String)>),
    UpdateDownload(Option<f64>, Option<String>),
    DownloadCompleted(String),
    DownloadFailed(String),
    DownloadPaused(String),
    ClearDownload,
    CancelDownload,
    PromptDownloadEpisode,
    ConfirmDownloadEpisode,
    PromptDownloadSeason,
    ConfirmDownloadSeason,
    ProcessDownloadQueue,
    FetchDetails(String, bool),
    DetailsSuccess(
        pulse_core::providers::models::RequestContext,
        u64,
        String,
        Box<pulse_core::providers::models::MediaDetails>,
    ),
    DetailsFailure(pulse_core::providers::models::RequestContext, u64, String),
    InitStreamPool(String),
    StreamPoolInitialized(String, Vec<u32>),
    FetchEpisodeStreams {
        subject_id: String,
        season: usize,
        episode: usize,
        force_refresh: bool,
    },
    EpisodeStreamsReady(
        pulse_core::providers::models::RequestContext,
        u64,
        String,
        usize,
        usize,
        Vec<pulse_core::providers::models::Release>,
    ),
    EpisodeStreamsFailed(
        pulse_core::providers::models::RequestContext,
        u64,
        String,
        usize,
        usize,
        String,
    ),
    PosterSuccess(String, std::sync::Arc<image::DynamicImage>),
    SearchPosterLoaded(String, Option<std::sync::Arc<image::DynamicImage>>),
    UpdateAvailable(Result<Option<pulse_core::updater::Release>, String>),
    CheckForUpdates,
    StartSelfUpdate,
    SelfUpdateProgress(String),
    SelfUpdateComplete(Result<pulse_core::updater::SelfUpdateOutcome, String>),
    SetStatus(String),
    Refresh,
    ClearCache,
    CacheCleared(Result<(), String>),
    LaunchPlayback(
        crate::tui::state::PlayerKind,
        pulse_core::providers::models::PlaybackSource,
    ),
    DispatchPlayback(pulse_core::providers::models::PlaybackSource),
    MarkWatched(Box<pulse_core::history::WatchHistoryItem>),
    UpdateProgress {
        item: Box<pulse_core::history::WatchHistoryItem>,
        progress: u64,
        duration: Option<u64>,
        completed: bool,
    },
    ReconcileHistory,
    PlayerCrashed(Option<i32>, String),
    PlayerExited,
    ToggleFavorite,
    ShowFavorites,
    OpenFavorite(usize),
    OpenContinueWatching(usize),
    ToggleProvider(pulse_core::providers::models::ProviderKind),
    CheckBdixNetwork,
    BdixProbeResult {
        circleftp: bool,
        dhakaflix: bool,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_action_enum_size_bounded() {
        let size = std::mem::size_of::<Action>();
        assert!(size <= 128, "Action size is {size} bytes, expected <= 128");
    }
}
